# Generated by Django 4.2.24 on 2025-09-17 18:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("core", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Member",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "member_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Número de Socio"
                    ),
                ),
                (
                    "first_name",
                    models.CharField(max_length=100, verbose_name="Nombres"),
                ),
                (
                    "last_name",
                    models.CharField(max_length=100, verbose_name="Apellidos"),
                ),
                (
                    "email",
                    models.EmailField(blank=True, max_length=255, verbose_name="Email"),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True, max_length=50, verbose_name="Teléfono"
                    ),
                ),
                (
                    "birth_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Fecha de Nacimiento"
                    ),
                ),
                ("join_date", models.DateField(verbose_name="Fecha de Ingreso")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("ACTIVE", "Activo"),
                            ("INACTIVE", "Inactivo"),
                            ("SUSPENDED", "Suspendido"),
                        ],
                        default="ACTIVE",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="members",
                        to="core.club",
                        verbose_name="Club",
                    ),
                ),
                (
                    "user_account",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="member_profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Cuenta de Usuario",
                    ),
                ),
            ],
            options={
                "verbose_name": "Socio",
                "verbose_name_plural": "Socios",
                "ordering": ["last_name", "first_name"],
                "unique_together": {("club", "member_number")},
            },
        ),
    ]
