# Generated by Django 4.2.24 on 2025-09-17 18:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_member"),
    ]

    operations = [
        migrations.CreateModel(
            name="Fee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Descripción"),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Monto"
                    ),
                ),
                ("due_date", models.DateField(verbose_name="Fecha de Vencimiento")),
                ("period", models.DateField(verbose_name="Período al que corresponde")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("PAID", "Pagada"),
                            ("CANCELED", "Anulada"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Estado",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fees",
                        to="core.member",
                        verbose_name="Socio",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cuota",
                "verbose_name_plural": "Cuotas",
                "ordering": ["-due_date"],
            },
        ),
    ]
