# Generated by Django 4.2.24 on 2025-09-18 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_payment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="member_number",
            field=models.IntegerField(
                blank=True, editable=False, null=True, verbose_name="Número de Socio"
            ),
        ),
    ]
