# Generated by Django 4.2.24 on 2025-10-05 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_activity_member_activities"),
    ]

    operations = [
        migrations.AddField(
            model_name="club",
            name="base_membership_fee",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=10,
                verbose_name="Cuota Societaria Base",
            ),
        ),
    ]
